name: Mirror assets to S3

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Mirror assets
        run: |
          function putS3 {
            path=$1
            file=$2
            aws_path='/assets/qualtrics/'
            bucket='files.consumerfinance.gov'
            date=$(date +"%a, %d %b %Y %T %z")
            content_type='text/css'
            string="PUT\n\n$content_type\n$date\n/$bucket$aws_path$file"
            signature=$(echo -en "${string}" | openssl sha1 -hmac "${{secrets.S3SECRET}}" -binary | base64)
            curl -X PUT -k -v -T "$path/$file" \
              -H "Host: $bucket.s3.amazonaws.com" \
              -H "Date: $date" \
              -H "Content-Type: $content_type" \
              -H "Authorization: AWS ${{secrets.S3KEY}}:$signature" \
              "https://$bucket.s3.amazonaws.com$aws_path$file"
          }

          for file in "src/*"; do
            putS3 "src" "${file##*/}"
          done
